import { Inter, MuseoModerno } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],

  variable: "--normal-font",
});

const museoModerno = MuseoModerno({
  subsets: ["latin"],

  variable: "--curvy-font",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${museoModerno.variable} ${inter.variable}`}>
      
      <body>{children}</body>
    </html>
  );
}
